function [data] = flex_wv(zk,coefs,dir,targs)

    np = size(targs.r(:,:),2);
%np=1;
    nx = targs.n(1,:).'; 
    ny = targs.n(2,:).';
    kappa = targs.kappa(:);
    dx = targs.d(1,:).';
    dy = targs.d(2,:).';
    
    ds = sqrt(dx.*dx+dy.*dy);
    taux = (dx./ds);                                                                       % normalization
    tauy = (dy./ds);
    
    zdot = dir(1)*targs.r(1,:)+dir(2)*targs.r(2,:);
    zdot = zdot.';
    zexp = exp(1i*zk*zdot);
    firstbc = (nx*dir(1)+ny*dir(2)).^2 + coefs(1)*(taux*dir(1)+tauy*dir(2)).^2;
    firstbc = firstbc.*(-zk^2).*zexp;
    secondbc = -1i*zk^3*(nx*dir(1)+ny*dir(2)).^3 + ...
        -1i*zk^3*(2-coefs(1))*(nx*dir(1)+ny*dir(2)).*(taux*dir(1)+tauy*dir(2)).^2 + ...
        (-zk^2)*(1-coefs(1))*kappa.*(-(nx*dir(1)+ny*dir(2)).^2 + (taux*dir(1)+tauy*dir(2)).^2);
    secondbc = secondbc.*zexp;
    % firstbc = 1/(2*zk^2).*(hess(:, :, 1).*(nx.*nx) + hess(:, :, 2).*(2*nx.*ny) + hess(:, :, 3).*(ny.*ny))-...
    %            1/(2*zk^2).*(hessK(:, :, 1).*(nx.*nx) + hessK(:, :, 2).*(2*nx.*ny) + hessK(:, :, 3).*(ny.*ny))+...
    %            coefs(1)/(2*zk^2).*(hess(:, :, 1).*(taux.*taux) + hess(:, :, 2).*(2*taux.*tauy) + hess(:, :, 3).*(tauy.*tauy))-...
    %            coefs(1)/(2*zk^2).*(hessK(:, :, 1).*(taux.*taux) + hessK(:, :, 2).*(2*taux.*tauy) + ...
    %            hessK(:, :, 3).*(tauy.*tauy));
    % 
    % secondbc = 1./(2*zk^2).*(third(:, :, 1).*(nx.*nx.*nx) + third(:, :, 2).*(3*nx.*nx.*ny) +...
    %        third(:, :, 3).*(3*nx.*ny.*ny) + third(:, :, 4).*(ny.*ny.*ny)) - ...
    %         1./(2*zk^2).*(thirdK(:, :, 1).*(nx.*nx.*nx) + thirdK(:, :, 2).*(3*nx.*nx.*ny)+...
    %         thirdK(:, :, 3).*(3*nx.*ny.*ny) + thirdK(:, :, 4).*(ny.*ny.*ny)) +...
    %         (2-coefs(1))/(2*zk^2).*(third(:, :, 1).*(taux.*taux.*nx) + third(:, :, 2).*(taux.*taux.*ny + 2*taux.*tauy.*nx) +...
    %         third(:, :, 3).*(2*taux.*tauy.*ny+ tauy.*tauy.*nx) +...
    %         + third(:, :, 4).*(tauy.*tauy.*ny)) - ...
    %         (2-coefs(1))/(2*zk^2).*(thirdK(:, :, 1).*(taux.*taux.*nx) + thirdK(:, :, 2).*(taux.*taux.*ny + 2*taux.*tauy.*nx) +...
    %         thirdK(:, :, 3).*(2*taux.*tauy.*ny+ tauy.*tauy.*nx) +...
    %         + thirdK(:, :, 4).*(tauy.*tauy.*ny)) +...
    %         (1-coefs(1))*diag(kappa)*(1/(2*zk^2).*(hess(:, :, 1).*taux.*taux + hess(:, :, 2).*(2*taux.*tauy) + hess(:, :, 3).*tauy.*tauy)-...
    %          1/(2*zk^2).*(hessK(:, :, 1).*taux.*taux + hessK(:, :, 2).*(2*taux.*tauy) + ...
    %         hessK(:, :, 3).*tauy.*tauy)-...
    %         (1/(2*zk^2).*(hess(:, :, 1).*nx.*nx + hess(:, :, 2).*(2*nx.*ny) + hess(:, :, 3).*ny.*ny)-...
    %        1/(2*zk^2).*(hessK(:, :, 1).*nx.*nx + hessK(:, :, 2).*(2*nx.*ny) + hessK(:, :, 3).*ny.*ny)));

    data = zeros(2*np, 1);
    data(1:2:end,:) = firstbc;
    data(2:2:end,:) = secondbc;



end